Repository part4-team5/checkmate, pull requests merged in 2024-08, with the labels that each got.

#15 ✨ Feat: 랜딩 페이지 제작
  app/page.tsx
  public/icons/.gitkeep
  public/icons/CheckedIcon.svg
  public/icons/FolderIcon.svg
  public/icons/MailIcon.svg
  public/icons/RepairIcon.svg
  public/images/.gitkeep
  public/images/landing_1.webp
  public/images/landing_2.webp
  public/images/landing_3.webp
  public/images/landing_footer.webp
  public/images/landing_main.webp
  tailwind.config.ts
Labels: ✨feat

#24 🐛 Fix: 팝오버 수정
  .eslintrc
  .github/ISSUE_TEMPLATE/♻️-refactor-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/⚠️-dependency-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/✨-feat-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/❓-question--이슈-템플릿.md
  .github/ISSUE_TEMPLATE/🐛-fix-리포트-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/💄-style--이슈-템플릿.md
  app/_components/Popover.tsx
Labels: 🐛fix

#23 ✨ Feat: storybook 추가
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  stories/Button.stories.tsx
  stories/Popover.stories.tsx
  tailwind.config.ts
  tsconfig.json
Labels: ✨feat

#19 ✨ Feat: 모달기능 추가
  .husky/pre-commit
  app/_components/GlobalModals.tsx
  app/_components/modal-contents/AccountDeletion.tsx
  app/_components/modal-contents/Logout.tsx
  app/_components/modal-contents/MemberInvite.tsx
  app/_hooks/useOverlay.ts
  app/_store/modalStore.ts
  app/layout.tsx
  package-lock.json
  package.json
  public/icons/ic_close.tsx
  public/icons/ic_warning.tsx
  tailwind.config.ts
Labels: ✨feat

#28 ✨ Feat: 드롭다운 컴포넌트
  app/_components/Dropdown.tsx
  app/_components/Popover.tsx
  public/icons/CheckIcon.tsx
  public/icons/GearIcon.tsx
  public/icons/KebabIcon.tsx
  public/icons/PlusIcon.tsx
Labels: ✨feat

#34 ✨ feat: 페이지 추가
  app/(auth)/login/page.tsx
  app/(auth)/mypage/page.tsx
  app/(auth)/oauth/signup/[provider]/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/(community)/addboard/page.tsx
  app/(community)/board/[board-id]/page.tsx
  app/(community)/boards/page.tsx
  app/[team-id]/page.tsx
  app/[team-id]/tasks/page.tsx
  app/addteam/page.tsx
  app/layout.tsx
  stories/Popover.stories.tsx
Labels: ✨feat

#29 ✨ feat : 비밀번호 재설정 페이지 추가
  app/(auth)/reset-password/page.tsx
  app/_components/QureyProvider.tsx
  app/layout.tsx
  package-lock.json
  package.json
Labels: ✨feat

#36 ✨ Feat: 캘린더 컴포넌트 추가
  .eslintrc
  app/_components/Calendar.tsx
  public/icons/ArrowLeftIcon.tsx
  public/icons/ArrowRightIcon.tsx
Labels: ✨feat

#37 ✨ Feat: 스토리북 수정
  app/_components/Button.tsx
  app/_components/Dropdown.tsx
  app/_components/Popover.tsx
  package-lock.json
  package.json
  stories/Button.stories.tsx
  stories/Dropdown.stories.tsx
  stories/Modal.stories.tsx
  stories/Popover.stories.tsx
Labels: ✨feat, 🐛fix

#44 ✨ Feat: useCookie, useCrossState
  .husky/pre-commit
  app/_api/index.ts
  app/_hooks/useCookie.tsx
  app/_hooks/useCrossState.tsx
  app/_utils/Cookie.ts
Labels: ✨feat

#21 ✨Feat: Message 공용 컴포넌트 추가
  app/_components/Author.tsx
  app/_components/Message.tsx
  public/icons/ic_comment.tsx
  public/icons/ic_heart.tsx
  public/images/profile.png
Labels: ✨feat

#31 ✨ Feat: Header 공통 컴포넌트 제작
  app/_components/header.tsx
  app/layout.tsx
  public/icons/CheckIcon.tsx
  public/icons/LogoTypoIcon.tsx
  public/icons/MenuIcon.tsx
  public/icons/UserIcon.tsx
Labels: ✨feat

#47 ✨ feat : 팀 생성, 수정, 참여, 빈 페이지 제작
  app/(team)/(team-potal)/create-team/layout.tsx
  app/(team)/(team-potal)/create-team/page.tsx
  app/(team)/(team-potal)/join-team/layout.tsx
  app/(team)/(team-potal)/join-team/page.tsx
  app/(team)/[id]/edit/_components/EditForm.tsx
  app/(team)/[id]/edit/layout.tsx
  app/(team)/[id]/edit/page.tsx
  app/(team)/create-team/page.tsx
  app/(team)/team-hub/page.tsx
  app/_api/index.ts
  app/_components/Form.tsx
  app/_components/QueryProvider.tsx
  app/_components/QureyProvider.tsx
  app/_utils/Cookie.ts
  app/layout.tsx
  next.config.mjs
  public/icons/editIcon.svg
  public/icons/imageIcon.svg
  public/images/teamEmpty.webp
Labels: ✨feat

#48 ✨ feat: Report 컴포넌트 구현
  app/(team)/[id]/_component/CircularProgressBar.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/layout.tsx
  app/(team)/[id]/page.tsx
  app/_api/index.ts
  app/layout.tsx
  public/icons/DoneIcon.svg
  public/icons/TodoIcon.svg
  tailwind.config.ts
Labels: ✨feat

#51 🐛 fix : 앱 라우터 서버 초기 데이터 캐싱 문제 해결
  app/(team)/(team-potal)/create-team/page.tsx
  app/(team)/(team-potal)/join-team/page.tsx
  app/(team)/[id]/edit/_components/EditForm.tsx
  app/(team)/[id]/edit/page.tsx
  app/(team)/create-team/layout.tsx
  app/(team)/create-team/page.tsx
  app/(team)/get-started/page.tsx
  app/(team)/join-team/layout.tsx
  app/(team)/join-team/page.tsx
  app/(team)/layout.tsx
  app/(team)/team-hub/page.tsx
  app/_api/index.ts
  app/_components/Form.tsx
  app/_components/GetQueryClient.tsx
  app/_components/QueryProvider.tsx
  app/_components/QureyProvider.tsx
  app/_components/header.tsx
  app/page.tsx
  public/icons/edit.svg
  public/icons/emptyImage.svg
  public/icons/landingChecked.svg
  public/icons/landingFolder.svg
  public/icons/landingMail.svg
  public/icons/landingRepair.svg
Labels: 🐛fix

#61 Refactor: 모달 ui ModalWrapper로 분리
  app/(team)/[id]/_component/Report.tsx
  app/_components/GlobalModals.tsx
  app/_components/modal-contents/AccountDeletion.tsx
  app/_components/modal-contents/Logout.tsx
  app/_components/modal-contents/MemberInvite.tsx
  app/_components/modal-contents/Modal.tsx
  app/_hooks/useOverlay.ts
  app/_store/modalStore.ts
  package-lock.json
Labels: ♻️refactor

#64 ✨ feat: Members 컴포넌트 구현
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/UserInfo.tsx
  app/(team)/[id]/page.tsx
  app/_components/Author.tsx
  app/_components/Dropdown.tsx
  app/_components/modal-contents/MemberInvite.tsx
  app/_components/modal-contents/MemberProfile.tsx
  public/icons/defaultAvatar.svg
Labels: ✨feat

#68 ♻️ refactor: 드롭다운 개선
  app/(user)/my-history/page.tsx
  app/_components/Dropdown.tsx
  app/_components/Popover.tsx
  app/_components/header.tsx
  public/images/Frame.png
  stories/Dropdown.stories.tsx
  stories/Popover.stories.tsx
  tailwind.config.ts
Labels: ♻️refactor

#63 ✨ Feat : 비밀번호 재설정 페이지 기능 수정
  .gitignore
  app/(auth)/reset-password/page.tsx
  app/(team)/[id]/edit/_components/EditForm.tsx
  app/(team)/[id]/edit/page.tsx
  app/(team)/[id]/layout.tsx
  app/(team)/create-team/page.tsx
  app/(team)/join-team/page.tsx
  app/_api/index.ts
Labels: ✨feat, 🐛fix, ♻️refactor

#71 🐛 fix : 코드가 날아가는 문제 수정
  app/(board)/boards/[id]/page.tsx
  app/(board)/boards/page.tsx
  app/(board)/create-post/page.tsx
  app/(team)/[id]/layout.tsx
  app/(team)/create-team/layout.tsx
Labels: 🐛fix

#69 ♻️ refactor : 팀 참가 및 시작 페이지 수정
  app/(team)/[id]/edit/_components/EditForm.tsx
  app/(team)/[id]/edit/page.tsx
  app/(team)/create-team/page.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/(team)/get-started/page.tsx
  app/(team)/join-team/page.tsx
  app/_api/index.ts
  tailwind.config.ts
Labels: ✨feat, ♻️refactor

#56 ✨ feat: 리스트페이지 작업
  app/(team)/[id]/todo/_components/AddTask.tsx
  app/(team)/[id]/todo/_components/DateTimeFrequency.tsx
  app/(team)/[id]/todo/_components/TodoItem.tsx
  app/(team)/[id]/todo/_components/api/queryFactory.ts
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(team)/[id]/todo/_components/api/useQuery.ts
  app/(team)/[id]/todo/_components/todo.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/(team)/[id]/todo/page.tsx
  app/_api/index.ts
  app/_components/GlobalModals.tsx
  app/_components/sidebar.tsx
  app/_icons/index.tsx
  app/_utils/IsoToFriendlyDate.ts
  public/icons/addComment.svg
  public/icons/calendar.svg
  public/icons/calendarCircle.svg
  public/icons/calendarLeftArrow.svg
  public/icons/calendarRightArrow.svg
  public/icons/checkBox.svg
  public/icons/clock.svg
  public/icons/comment.svg
  public/icons/cycles.svg
  public/icons/defaultAvatar.svg
  public/icons/disableAddComment.svg
  public/icons/uncheckBox.svg
Labels: ✨feat

#74 ✨ Feat : 소셜 로그인 기능 추가
  app/(auth)/_components/Oauth.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/google/page.tsx
  app/(auth)/login/kakao/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(team)/join-team/page.tsx
  app/_api/index.ts
  app/_components/QueryProvider.tsx
  app/_components/header.tsx
  public/icons/google.svg
  public/icons/kakaotalk.svg
Labels: ✨feat

#76 ♻️ refactor : 중간 점검 반영
  app/(auth)/_components/Oauth.tsx
  app/(auth)/login/google/page.tsx
  app/(auth)/login/kakao/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/(team)/join-team/page.tsx
  app/_components/header.tsx
  app/page.tsx
Labels: ♻️refactor, 💄style

#79 ✨ Feat : 할 일 추가 모달 제작
  app/(team)/[id]/todo/_components/AddTodo.tsx
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(team)/[id]/todo/_components/todo.tsx
  app/_api/index.ts
  app/_components/modal-contents/Modal.tsx
  app/_icons/index.tsx
Labels: ✨feat

#81 ✨ feat: 드래그엔 드롭 구현
  app/(team)/[id]/todo/_components/AddTask.tsx
  app/(team)/[id]/todo/_components/TodoItem.tsx
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(team)/[id]/todo/_components/todo.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/_api/index.ts
  app/_components/sidebar.tsx
  public/icons/loading.svg
  public/icons/spinner.svg
Labels: ✨feat, 🐛fix

#73 ✨ Feat: 게시글 추가 페이지 제작
  .env
  .env.local
  .eslintrc
  .gitignore
  app/(board)/create-post/page.tsx
  app/(user)/my-history/page.tsx
  app/_api/index.ts
  app/_components/Calendar.tsx
  app/_components/Quill.tsx
  app/_components/Switch.tsx
  app/_icons/index.tsx
  app/_utils/Capsule.ts
  app/globals.css
  package-lock.json
  package.json
Labels: ✨feat

#80 ✨ feat: 계정 설정, 회원 탈퇴, 비밀번호 변경 추가
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(user)/my-page/page.tsx
  app/_components/modal-contents/ChangePassword.tsx
  public/icons/ic_delete.svg
  public/images/reset_password.png
Labels: ✨feat

#84 ✨ feat : Middleware 설정
  .env
  .env.local
  .gitignore
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/page.tsx
  middleware.ts
Labels: ✨feat

#82 ✨ feat: TeamTitile & Tasks 컴포넌트 구현
  app/(team)/[id]/_component/CircularProgressBar.tsx
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/TeamTitle.tsx
  app/(team)/[id]/_component/ToastPopup.tsx
  app/(team)/[id]/_component/UserInfo.tsx
  app/(team)/[id]/page.tsx
  app/_api/index.ts
  app/_components/Dropdown.tsx
  app/_components/Form.tsx
  app/_components/modal-contents/DeleteModal.tsx
  app/_components/modal-contents/PostEditTasks.tsx
  app/_components/modal-contents/TeamEdit.tsx
  app/_icons/index.tsx
  public/icons/DoneCheckIcon.svg
Labels: ✨feat

#86 ✨Feat: 할일 삭제, 댓글 수정, 댓글 삭제
  app/(team)/[id]/todo/_components/AddTask.tsx
  app/(team)/[id]/todo/_components/TodoDetailCommentList.tsx
  app/(team)/[id]/todo/_components/TodoDetailHeader.tsx
  app/(team)/[id]/todo/_components/TodoDetailInput.tsx
  app/(team)/[id]/todo/_components/TodoItem.tsx
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(team)/[id]/todo/_components/todo.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/_api/index.ts
  app/_components/modal-contents/Modal.tsx
  app/_icons/index.tsx
Labels: ✨feat, ♻️refactor

#85 ♻️ refactor : 팀 생성, 참가 페이지, 헤더 수정
  app/(team)/create-team/page.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/(team)/get-started/layout.tsx
  app/(team)/get-started/page.tsx
  app/(team)/join-team/layout.tsx
  app/(team)/join-team/page.tsx
  app/_components/Button.tsx
  app/_components/header.tsx
  app/layout.tsx
  next.config.mjs
  public/icons/add.svg
  public/icons/box.svg
  public/icons/list.svg
Labels: ♻️refactor

#90 ♻️ refactor : 점검 사항 수정
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(user)/my-page/page.tsx
  app/_components/header.tsx
  app/_components/modal-contents/AccountDeletion.tsx
  app/_utils/DelayManager.ts
  app/_utils/debounce.ts
  app/page.tsx
  middleware.ts
  next.config.mjs
Labels: ♻️refactor

#91 최종점검 반영
  app/(board)/boards/page.tsx
  app/(board)/create-post/page.tsx
  app/_components/Calendar.tsx
  app/globals.css
  package-lock.json
  package.json
Labels: ✨feat, 🐛fix

#95 ♻️ refactor : 팀 페이지 개선 사항 반영
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/TeamTitle.tsx
  app/(team)/[id]/_component/ToastPopup.tsx
  app/(team)/[id]/_component/UserInfo.tsx
  app/(team)/[id]/_component/useTaskList.ts
  app/_components/Dropdown.tsx
  app/_components/Popover.tsx
  app/_components/modal-contents/MemberInvite.tsx
  app/_components/modal-contents/Modal.tsx
  app/_components/modal-contents/PostEditTasks.tsx
  app/_components/modal-contents/TeamEdit.tsx
  app/_icons/index.tsx
  next.config.mjs
Labels: ✨feat, 🐛fix, ♻️refactor, 💄style

#92 ✨ Feat: 자유게시판 상세페이지
  .vscode/settings.json
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/[id]/page.tsx
  app/_api/index.ts
  app/_components/Message.tsx
  app/_icons/index.tsx
  tailwind.config.ts
Labels: ✨feat

#94 ♻️ Refactor: 디자인 수정 + 호버 오류 수정 + 할일 삭제모달 추가
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/useTaskList.ts
  app/(team)/[id]/page.tsx
  app/(team)/[id]/todo/_components/AddTask.tsx
  app/(team)/[id]/todo/_components/DateTimeFrequency.tsx
  app/(team)/[id]/todo/_components/TodoDetailCommentList.tsx
  app/(team)/[id]/todo/_components/TodoDetailHeader.tsx
  app/(team)/[id]/todo/_components/TodoItem.tsx
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(team)/[id]/todo/_components/api/useQuery.ts
  app/(team)/[id]/todo/_components/todo.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/(team)/[id]/todo/page.tsx
  app/_components/modal-contents/DeleteModal.tsx
  app/_components/sidebar.tsx
  app/_icons/index.tsx
  app/_utils/IsoToFriendlyDate.ts
Labels: 🐛fix, ♻️refactor, 💄style

#103 ♻️ Refactor: 최종 점검 수정사항 반영
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/[id]/page.tsx
  app/(user)/my-page/page.tsx
Labels: ♻️refactor

#105 ✨ feat : toast 기능 추가
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/TeamTitle.tsx
  app/(team)/[id]/_component/ToastPopup.tsx
  app/_components/Toaster.tsx
  app/_components/modal-contents/PostEditTasks.tsx
  app/_icons/index.tsx
  app/_store/toastStore.ts
  app/_utils/Toast.ts
  app/layout.tsx
Labels: ✨feat

#104 💄 ui: 애니메이션 추가 스켈레톤 수정
  app/(team)/[id]/todo/_components/AddTask.tsx
  app/(team)/[id]/todo/_components/TodoItem.tsx
  app/(team)/[id]/todo/_components/todo.tsx
  app/_components/Button.tsx
  app/_components/Popover.tsx
  app/_icons/index.tsx
Labels: ✨feat, 💄style

#112 ✨ feat : 다크모드 색상 설정
  app/(auth)/_components/Oauth.tsx
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/[id]/page.tsx
  app/(board)/boards/page.tsx
  app/(team)/[id]/edit/_components/EditForm.tsx
  app/(team)/create-team/page.tsx
  app/(user)/my-page/page.tsx
  app/_components/header.tsx
  app/_components/modal-contents/TeamEdit.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  tailwind.config.ts
Labels: ✨feat

#108 ♻️ refactor: 드롭다운 개선 사항 반영
  app/(board)/boards/page.tsx
  app/_components/Dropdown.tsx
  app/_components/header.tsx
  app/_components/modal-contents/DeleteModal.tsx
Labels: 🐛fix, ♻️refactor

#106 ♻️ Refactor : 최종 점검 반영
  app/(auth)/_components/Oauth.tsx
  app/(auth)/login/google/page.tsx
  app/(auth)/login/kakao/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/(team)/[id]/edit/_components/EditForm.tsx
  app/(team)/[id]/edit/layout.tsx
  app/(team)/[id]/edit/page.tsx
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/(team)/create-team/page.tsx
  app/_api/index.ts
  app/_components/DarkModeTogle.tsx
  app/_components/Dropdown.tsx
  app/_components/Toaster.tsx
  app/_components/header.tsx
  app/_icons/index.tsx
  app/_utils/Cookie.ts
  app/_utils/Token.ts
  app/layout.tsx
Labels: 🐛fix, ♻️refactor

#115 💄 style: boxShadow 추가
  app/globals.css
  tailwind.config.ts
Labels: 💄style

#110 ♻️ refactor : 팀 수정 모달, 팀 페이지 개선
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/_components/modal-contents/TeamEdit.tsx
Labels: 🐛fix, ♻️refactor, 💄style

#117 ♻️ refactor: 토스트 팝업 적용, 디자인 적용, 사이드바 아이콘 변경
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/[id]/_components/Skeletion.tsx
  app/(board)/boards/[id]/page.tsx
  app/(user)/my-page/page.tsx
  app/_api/index.ts
  app/_components/header.tsx
  public/icons/bigLogo.svg
  public/icons/board.svg
  public/icons/teamAdd.svg
  public/icons/teamList.svg
Labels: ♻️refactor

#107 ✨ feat: tour
  app/(board)/create-post/page.tsx
  app/_components/Button.tsx
  app/_components/Popover.tsx
  app/_components/Quill.tsx
  app/_utils/Tour.tsx
Labels: ✨feat

#120 랜딩페이지 디자인 수정
  app/(board)/boards/page.tsx
  app/(board)/create-post/page.tsx
  app/(team)/[id]/_component/CircularProgressBar.tsx
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/[id]/todo/_components/todo.tsx
  app/(team)/create-team/page.tsx
  app/(team)/get-started/_components/InvitedList.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/(team)/join-team/_components/JoinTeam.tsx
  app/_components/Button.tsx
  app/_components/DarkModeToggle.tsx
  app/_components/LandingProgressBar.tsx
  app/_components/Toaster.tsx
  app/_components/header.tsx
  app/_icons/index.tsx
  app/globals.css
  app/page.tsx
  public/icons/CheckIcon.tsx
  public/icons/add.svg
  public/icons/landingCheck.svg
  tailwind.config.ts
Labels: ♻️refactor, 💄style

#124 style: 이것저것
  app/(board)/create-post/page.tsx
  app/_components/Message.tsx
  app/_utils/Tour.tsx
  package-lock.json
  package.json
Labels: 💄style

#121 💄Style : 드롭다운다크모드
  app/(team)/[id]/_component/Tasks.tsx
  app/_components/Dropdown.tsx
  app/_components/Popover.tsx
  app/_icons/index.tsx
  app/globals.css
Labels: 💄style

#125 style: form 자동완성 수정
  app/(board)/boards/page.tsx
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/UserInfo.tsx
  app/_utils/Tour.tsx
  app/globals.css
Labels: 💄style

#123 💄 style : 시작하기 페이지 스켈레톤 수정
  app/(team)/get-started/_components/InvitedList.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/_components/DarkModeToggle.tsx
  app/_components/Toaster.tsx
  app/_components/header.tsx
  app/layout.tsx
Labels: 💄style

#126 style: 메인 랜딩페이지 수정
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/[id]/_components/Skeletion.tsx
  app/(board)/boards/[id]/page.tsx
  app/_components/LandingProgressBar.tsx
  app/_components/header.tsx
  app/_icons/index.tsx
  app/globals.css
  app/page.tsx
  package-lock.json
  package.json
  public/icons/facebook.svg
  public/icons/instagram.svg
  public/icons/mail.svg
  public/icons/mvCheck.svg
  public/images/main_bottom.png
  public/images/point1_dark.png
  public/images/point1_light.png
  public/images/point2_dark.png
  public/images/point2_icon.png
  public/images/point2_light.png
  public/images/point3_dark.png
  public/images/point3_icon.png
  public/images/point3_light.png
  tailwind.config.ts
Labels: 💄style

#130 feat: 이것저것
  app/(board)/create-post/page.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/UserInfo.tsx
  app/_components/Quill.tsx
  app/globals.css
  app/not-found.tsx
Labels: ✨feat

#129 💄 style : 헤더, 드롭다운 디자인 수정
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/TeamTitle.tsx
  app/(team)/[id]/page.tsx
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/(team)/create-team/page.tsx
  app/(team)/get-started/_components/InvitedList.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/(team)/join-team/_components/JoinTeam.tsx
  app/(user)/my-page/page.tsx
  app/_components/Dropdown.tsx
  app/_components/Form.tsx
  app/_components/header.tsx
  app/_components/modal-contents/MemberProfile.tsx
  app/_components/modal-contents/PostEditTasks.tsx
  app/_components/modal-contents/TeamEdit.tsx
  app/_icons/index.tsx
  app/globals.css
  public/icons/emptyImage.svg
  public/icons/ic_close.tsx
  public/icons/logo.svg
  tailwind.config.ts
Labels: 💄style

#133 style: 이것저것
  app/(board)/boards/page.tsx
  app/(board)/create-post/page.tsx
  app/globals.css
Labels: 💄style

#132 💄 style : 헤더, 모달 디자인 수정
  app/(user)/my-page/page.tsx
  app/_api/index.ts
  app/_components/header.tsx
  app/_components/modal-contents/Modal.tsx
  app/_components/modal-contents/TeamEdit.tsx
Labels: 💄style

#134 style: 이것저것
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/page.tsx
  app/(board)/create-post/page.tsx
  app/_components/Toaster.tsx
  app/_components/header.tsx
Labels: 💄style

#128 ✨ feat:투어 기능추가
  app/(team)/[id]/todo/_components/AddTodo.tsx
  app/(team)/[id]/todo/_components/TodoDetailCommentList.tsx
  app/(team)/[id]/todo/_components/TodoItem.tsx
  app/(team)/[id]/todo/_components/todo.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/_components/Popover.tsx
Labels: ✨feat

#138 🐛 fix : Popover 앵커 위치가 이상해서 롤백
  app/_components/Popover.tsx
Labels: 🐛fix

#141 ♻️ refactor : 초대 키 값 8자로 제한 및 할일 완료 시 내 히스토리 업데이트
  app/(team)/[id]/todo/_components/api/useMutation.ts
  app/api/invite/link/route.ts
  app/api/invite/route.ts
  app/api/users/[id]/groupId/[groupId]/route.ts
  app/api/users/route.ts
Labels: ♻️refactor

#143 fix: 자유게시판 버그 수정
  app/(board)/boards/[id]/page.tsx
Labels: 🐛fix

#146 🐛 fix : 팀 참가 안되는 버그 수정
  app/(team)/join-team/_components/JoinTeam.tsx
Labels: 🐛fix

#147 fix: metadata
  README.md
  app/layout.tsx
  package.json
Labels: 🐛fix

#148 deps: bump version
  package.json
Labels: ⚠️dependency
