Repository part4-team5/checkmate, pull requests merged in 2024-09, with the labels that each got.

#151 ♻️ refactor : 랜딩 페이지 이미지 다크모드 설정
  app/page.tsx
Labels: ♻️refactor

#152 🐛 fix: 드롭다운 이벤트 리스너 제거 로직 수정
  app/_components/Dropdown.tsx
Labels: 🐛fix

#153 ♻️ refactor : 버튼, 헤더, 토스트 수정
  app/_components/Button.tsx
  app/_components/Header/Sidebar.tsx
  app/_components/Header/index.tsx
  app/_components/Toaster.tsx
  app/_components/header.tsx
  app/_utils/Toast.ts
  app/layout.tsx
  tailwind.config.ts
Labels: ♻️refactor

#155 ♻️ refactor: 팀페이지
  app/(team)/[id]/_component/Members.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/_component/TeamTitle.tsx
  app/(team)/[id]/page.tsx
  app/_icons/index.tsx
Labels: ✨feat, ♻️refactor

#154 ♻️ refactor : 그룹 모델 추가 및 API 리팩토링
  app/(team)/[id]/_component/TeamTitle.tsx
  app/(team)/create-team/page.tsx
  app/(team)/get-started/_components/InvitedList.tsx
  app/_api/index.ts
  app/_components/modal-contents/MemberInvite.tsx
  app/_utils/_models/Group.model.ts
  app/_utils/_models/Invite.model.ts
  app/_utils/_models/Users.model.ts
  app/api/group/[groupId]/route.ts
  app/api/group/[groupId]/userId/[userId]/route.ts
  app/api/group/route.ts
  app/api/invite/[id]/groupId/[groupId]/route.ts
  app/api/invite/[id]/route.ts
  app/api/invite/link/[key]/route.ts
  app/api/invite/link/route.ts
  app/api/invite/route.ts
  app/api/users/[id]/groupId/[groupId]/route.ts
  app/api/users/[id]/route.ts
  app/api/users/route.ts
Labels: ♻️refactor

#156 ♻️ refactor : 아이콘, 이미지 파일 수정
  .vscode/settings.json
  app/(board)/boards/[id]/_components/BoardDetailComments.tsx
  app/(board)/boards/[id]/page.tsx
  app/(board)/boards/page.tsx
  app/(team)/[id]/_component/Report.tsx
  app/(team)/[id]/_component/Tasks.tsx
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/[id]/todo/_components/TodoDetailCommentList.tsx
  app/(team)/[id]/todo/_components/todoDetail.tsx
  app/(user)/my-page/page.tsx
  app/_components/Calendar.tsx
  app/_components/Dropdown.tsx
  app/_components/Form.tsx
  app/_components/Header/Sidebar.tsx
  app/_components/Header/index.tsx
  app/_components/LandingProgressBar.tsx
  app/_components/Message.tsx
  app/_components/modal-contents/AccountDeletion.tsx
  app/_icons/index.tsx
  app/favicon.ico
  app/page.tsx
  public/icons/ArrowLeftIcon.tsx
  public/icons/ArrowRightIcon.tsx
  public/icons/CheckIcon.tsx
  public/icons/DoneCheckIcon.svg
  public/icons/GearIcon.tsx
  public/icons/HideIcon.tsx
  public/icons/KebabIcon.tsx
  public/icons/PlusIcon.tsx
  public/icons/ShowIcon.tsx
  public/icons/box.svg
  public/icons/calendarCircle.svg
  public/icons/calendarLeftArrow.svg
  public/icons/calendarRightArrow.svg
  public/icons/delete.svg
  public/icons/done.svg
  public/icons/edit.svg
  public/icons/ic_comment.tsx
  public/icons/ic_heart.tsx
  public/icons/ic_warning.tsx
  public/icons/landingCheck.svg
  public/icons/landingChecked.svg
  public/icons/landingFolder.svg
  public/icons/landingMail.svg
  public/icons/landingRepair.svg
  public/icons/list.svg
  public/icons/mvCheck.svg
  public/icons/todo.svg
  public/images/Frame.png
  public/images/landing_1.webp
  public/images/landing_2.webp
  public/images/landing_3.webp
  public/images/landing_footer.webp
  public/images/landing_main.webp
  public/images/medal.webp
  public/images/teamEmpty.webp
Labels: ♻️refactor

#158 ♻️ Refactor : 대시보드, 팀 생성, 팀 참가, 버튼, 할 일 추가 모달 수정
  app/(team)/[id]/todo/_components/AddTodoModal.tsx
  app/(team)/create-team/page.tsx
  app/(team)/get-started/_components/InvitedList.tsx
  app/(team)/get-started/_components/TeamLists.tsx
  app/(team)/join-team/[key]/_components/JoinTeam.tsx
  app/(team)/join-team/[key]/page.tsx
  app/(team)/join-team/page.tsx
  app/_components/Button.tsx
  app/_utils/Toast.ts
  app/api/invite/link/route.ts
  package-lock.json
Labels: ♻️refactor

#159 ✨ feat : README 작성
  README.md
  app/_api/.gitkeep
  app/_api/_models/Group.model.ts
  app/_api/_models/Invite.model.ts
  app/_api/_models/Users.model.ts
  app/_api/index.ts
  app/api/group/[groupId]/route.ts
  app/api/group/[groupId]/userId/[userId]/route.ts
  app/api/group/route.ts
  app/api/invite/[id]/groupId/[groupId]/route.ts
  app/api/invite/[id]/route.ts
  app/api/invite/link/[key]/route.ts
  app/api/invite/link/route.ts
  app/api/invite/route.ts
  app/api/users/[id]/route.ts
  app/api/users/route.ts
Labels: ✨feat

#161 💄style: 프로필 이미지 크기 조정
  app/(team)/[id]/_components/UserInfo.tsx
  app/_components/modals/modal-containers/MemberProfile.tsx
Labels: 💄style

#163 💄 style : 랜딩페이지 반응형 작업
  app/_components/LandingProgressBar.tsx
  app/page.tsx
Labels: 💄style

#164 ♻️ refactor : 할 일 페이지 수정
  app/(team)/[id]/todo/_components/Todo.tsx
  app/(team)/[id]/todo/_components/TodoDetail.tsx
  app/(team)/[id]/todo/_components/TodoDetailCommentInput.tsx
  app/(team)/[id]/todo/_components/TodoDetailCommentItem.tsx
  app/(team)/[id]/todo/_components/TodoDetailHeader.tsx
  app/(team)/[id]/todo/page.tsx
Labels: ♻️refactor

#165 💄 style : 계정 설정 페이지 수정
  app/(board)/boards/page.tsx
  app/(user)/my-page/page.tsx
  app/_components/modals/modal-containers/ChangePassword.tsx
  app/globals.css
Labels: 💄style

#166 ♻️ refactor : Popover, Tour 두 번째 위치를 지정할 수 있도록 수정
  app/(team)/[id]/_components/Report.tsx
  app/(team)/[id]/_components/Tasks.tsx
  app/(team)/[id]/page.tsx
  app/_components/Popover.tsx
  app/_utils/Tour.tsx
Labels: ♻️refactor
